### ISSUE TITLE
Drone docs

### ISSUE THREAD

**Issue by kneal** [codestation/drone-stack#1]
Do you have a plan to add the standard docs.md like all the other Drone plugins?

**Comment by codestation** [comment]
Yes, i was waiting until i had time to test without tls (for those that don't want to setup the whole cert stuff) before writting some proper docs. Now that there is one user i can be bothered to write something this weekend.

For now a very quick stuff that i use on my deploys:

``` yaml
  deploy:
    image: codestation/drone-stack
    host: tcp://example.com:2376
    stack_name: mystack
    tlsverify: true
    registry: registry.example.com
    secrets: [ docker_username, docker_password, docker_cert, docker_key, docker_cacert ]
```

Set the username and password (and registry) if you need to pull from a private registry. The docker_cert, docker_key and docker_cacert matches the cert.pem, key.pem and ca.pem files.

I will replace this with a link to the updated readme once i have written something better.
