### ISSUE TITLE
How to use with step/plugin syntax? drone:v1

### ISSUE THREAD

**Issue by decentral1se** [codestation/drone-stack#6]
https://docs.drone.io/pipeline/docker/syntax/steps/#plugins

I haven't been able to get it to work so far...

**Comment by decentral1se** [comment]
Intended syntax.

```yaml
kind: pipeline
name: deploy to foobar.com
steps:
  - name: deployment
    image: decentral1se/drone-stack:19.03.8-override-compose
    settings:
      compose: docker-compose.yml
      host: tcp://foobar.com:2376
      override_compose: docker-compose.production.yml
      stack_name: thing
      tlsverify: true
      docker_cacert:
        from_secret: docker_cacert
      docker_cert:
        from_secret: docker_cert
      docker_key:
        from_secret: docker_key
```

**Comment by decentral1se** [comment]
Error is always:

> time="2020-04-30T12:52:58Z" level=fatal msg="cannot setup certificates: cannot use tlsverify without a given CA"

**Comment by decentral1se** [comment]
Holy fuck I made it work.

```yaml
---
kind: pipeline
name: deploy to foobar.com
steps:
  - name: deployment
    image: decentral1se/drone-stack:19.03.8-override-compose
    settings:
      compose: docker-compose.yml
      host: tcp://foobar.com:2376
      override_compose: docker-compose.production.yml
      stack_name: thing
      tlsverify: true
    environment:
      PLUGIN_CACERT:
        from_secret: docker_cacert
      PLUGIN_CERT:
        from_secret: docker_cert
      PLUGIN_KEY:
        from_secret: docker_key
```

I suppose this is just a docs PR then. Will get to it another day.
